### ISSUE TITLE
Bundesländer: Flüsse der Hauptstädte hinzufügen?

### ISSUE THREAD

**Issue by jzaefferer** [loelschlaeger/ankidecks#1]
Danke für das tolle Bundesländer Deck! Definitiv unterbewertet auf https://ankiweb.net/

Würdest du zu den Bundesländern auch den Fluss, der durch die Hauptstadt fließt, hinzufügen?

Unvollständige Liste:
* BW / Neckar
* Bayern / Isar
* Berlin / Spree
* Brandenburg / Havel
* Bremen / Weser
* Hamburg / Elbe
* Hessen / Rhein
* Mecklenburg-Vorpommern / Schweriner See (und andere Seen, aber kein offensichtlicher Fluss)
* Niedersachsen / Leine, Ihme
* NRW / Rhein
* Rheinland-Pfalz / Rhein
* Saarland / Saar
* Sachsen / Elbe
* Sachsen-Anhalt / Elbe
* Schleswig-Holstein / Ostsee (auch kein offensichtlicher Fluss)
* Thüringen / (weder Fluss noch See noch Meer in Sicht, das einzige Gewässer heißt "Nordstrand")

**Comment by loelschlaeger** [comment]
Danke für die tolle Idee, das würde gut passen. Ich setze das gerne um, wenn ich dazu Zeit finde.

**Comment by jzaefferer** [comment]
Ich habe oben meine Liste vervollständigt. Nur Erfurt sieht wirklich dürftig aus, sonst gibt es meistens einen Fluss, mit Ausnahmen eines Sees oder Meers.

Da Rhein und Elbe gleich drei mal vorkommen, können diese Gewässer wohl nur auf eine Karten-Rückseite.

**Comment by loelschlaeger** [comment]
Das ergänzte Deck gibt es in 24 Stunden hier: https://ankiweb.net/shared/info/624857679 Danke nochmal für den Vorschlag und die Vorarbeit!

**Comment by jzaefferer** [comment]
Sehr cool 🤗👍
